input_boolean:
  door-opener-esp-online:
    icon: mdi:door-open

shell_command:
  turn_on_door_buzzer: curl -X POST http://<ESP-IP>/switch/relay/turn_on
  turn_off_door_buzzer: curl -X POST http://<ESP-IP>/switch/relay/turn_off

